/**
 * Test the appendWarningToNotionPage activity directly
 * This simulates how the activity is called in the workflow
 */

import { appendWarningToNotionPage } from '../../../worker/src/activities/notion.activities';

async function testActivity() {
  console.log('🧪 Testing appendWarningToNotionPage Activity...\n');

  const pageId = process.env.NOTION_PAGE_ID;

  if (!pageId) {
    console.error('❌ Missing NOTION_PAGE_ID');
    console.log('Usage: NOTION_API_KEY="..." NOTION_DATABASE_ID="..." NOTION_PAGE_ID="..." npx ts-node test-warning-activity.ts');
    process.exit(1);
  }

  try {
    // Test 1: Default message
    console.log('Test 1: Calling activity with default message...');
    await appendWarningToNotionPage({
      notionId: pageId,
    });
    console.log('✅ Activity executed successfully with default message!\n');

    // Test 2: Custom message
    console.log('Test 2: Calling activity with custom message...');
    await appendWarningToNotionPage({
      notionId: pageId,
      message: '🔒 This specification is locked. Contact DevFlow admin to make changes.',
    });
    console.log('✅ Activity executed successfully with custom message!\n');

    // Test 3: Using env variable
    console.log('Test 3: Testing with NOTION_SPEC_WARNING_MESSAGE env var...');
    process.env.NOTION_SPEC_WARNING_MESSAGE = '⚡ Generated by DevFlow AI - Do not modify manually!';
    await appendWarningToNotionPage({
      notionId: pageId,
    });
    console.log('✅ Activity executed successfully with env var message!\n');

    console.log('🎉 All activity tests passed!\n');
    console.log(`🔗 View results at: https://notion.so/${pageId.replace(/-/g, '')}`);
  } catch (error) {
    console.error('❌ Activity test failed:', error);
    if (error instanceof Error) {
      console.error('Error details:', error.message);
      console.error('Stack:', error.stack);
    }
    process.exit(1);
  }
}

testActivity();
