/**
 * Technical Plan Workflow - Phase 3 of Three-Phase Agile Workflow
 *
 * Generates detailed technical implementation plans from user stories.
 * Focus: Architecture, implementation steps, testing strategy, risk analysis
 * Uses RAG context for codebase-aware planning
 */

import { proxyActivities, ApplicationFailure } from '@temporalio/workflow';
import type { WorkflowConfig } from '@devflow/common';
import { DEFAULT_WORKFLOW_CONFIG } from '@devflow/common';
import type * as activities from '@/activities';

// Proxy activities with 10-minute timeout (RAG retrieval + AI generation takes longer)
const {
  syncLinearTask,
  updateLinearTask,
  retrieveContext,
  generateTechnicalPlan,
  appendTechnicalPlanToLinearIssue,
} = proxyActivities<typeof activities>({
  startToCloseTimeout: '10 minutes',
  retry: {
    maximumAttempts: 3,
  },
});

export interface TechnicalPlanWorkflowInput {
  taskId: string;
  projectId: string;
  config?: WorkflowConfig;
}

export interface TechnicalPlanWorkflowResult {
  success: boolean;
  phase: 'technical_plan';
  message: string;
  plan?: any;
}

/**
 * Extract user story from Linear issue description
 * TODO: Move to workflow helpers in Task 17
 */
function extractUserStoryFromDescription(description: string): any {
  // Simple extraction for now
  // The user story is appended as markdown in the format:
  // # User Story
  // > Generated by DevFlow - Phase 2: User Story
  // ...

  const userStoryMatch = description.match(/# User Story[\s\S]*?(?=\n# |$)/);
  if (!userStoryMatch) {
    // If no user story found, return minimal user story object
    return {
      userStory: {
        actor: 'user',
        goal: description.split('\n')[0] || 'Complete the task',
        benefit: 'improve the application',
      },
      acceptanceCriteria: [],
      definitionOfDone: [],
      businessValue: '',
      storyPoints: 5,
    };
  }

  const userStoryText = userStoryMatch[0];

  // Extract user story components
  const actorMatch = userStoryText.match(/\*\*As a\*\* ([^,\n]+)/);
  const goalMatch = userStoryText.match(/\*\*I want\*\* ([^,\n]+)/);
  const benefitMatch = userStoryText.match(/\*\*So that\*\* ([^.\n]+)/);

  const actor = actorMatch ? actorMatch[1].trim() : 'user';
  const goal = goalMatch ? goalMatch[1].trim() : '';
  const benefit = benefitMatch ? benefitMatch[1].trim() : '';

  // Extract acceptance criteria
  const criteriaMatch = userStoryText.match(/## Acceptance Criteria\n\n([\s\S]*?)(?=\n## |$)/);
  const acceptanceCriteria = criteriaMatch
    ? criteriaMatch[1]
        .split('\n')
        .filter((line) => line.match(/^\d+\./))
        .map((line) => line.replace(/^\d+\.\s*/, '').trim())
    : [];

  // Extract definition of done
  const dodMatch = userStoryText.match(/## Definition of Done\n\n([\s\S]*?)(?=\n## |$)/);
  const definitionOfDone = dodMatch
    ? dodMatch[1]
        .split('\n')
        .filter((line) => line.match(/^-/))
        .map((line) => line.replace(/^-\s*/, '').trim())
    : [];

  // Extract business value
  const businessValueMatch = userStoryText.match(/## Business Value\n\n([\s\S]*?)(?=\n## |$)/);
  const businessValue = businessValueMatch ? businessValueMatch[1].trim() : '';

  // Extract story points
  const storyPointsMatch = userStoryText.match(/\*\*Story Points:\*\* (\d+)/);
  const storyPoints = storyPointsMatch ? parseInt(storyPointsMatch[1], 10) : 5;

  return {
    userStory: {
      actor,
      goal,
      benefit,
    },
    acceptanceCriteria,
    definitionOfDone,
    businessValue,
    storyPoints,
  };
}

/**
 * Technical Plan Workflow
 * Phase 3: Create detailed technical implementation plan with codebase context
 */
export async function technicalPlanWorkflow(
  input: TechnicalPlanWorkflowInput
): Promise<TechnicalPlanWorkflowResult> {
  const config = input.config || DEFAULT_WORKFLOW_CONFIG;
  const LINEAR_STATUSES = config.linear.statuses;

  try {
    // Step 1: Sync task from Linear
    const task = await syncLinearTask({
      taskId: input.taskId,
      projectId: input.projectId,
    });

    // Step 2: Update status to Plan In Progress
    await updateLinearTask({
      projectId: input.projectId,
      linearId: task.linearId,
      updates: { status: LINEAR_STATUSES.planInProgress },
    });

    // Step 3: Retrieve RAG context for codebase analysis
    const ragContext = await retrieveContext({
      projectId: input.projectId,
      query: `${task.title}\n${task.description}`,
      topK: 10,
      useReranking: true,
    });

    // Step 4: Extract user story from Linear description
    const userStory = extractUserStoryFromDescription(task.description);

    // Step 5: Generate technical plan
    const result = await generateTechnicalPlan({
      task,
      projectId: input.projectId,
      userStory,
      ragContext,
    });

    // Step 6: Append technical plan to Linear issue
    await appendTechnicalPlanToLinearIssue({
      projectId: input.projectId,
      linearId: task.linearId,
      plan: result.plan,
      contextUsed: result.contextUsed,
      multiLLM: result.multiLLM,
    });

    // Step 7: Update status to Plan Ready
    await updateLinearTask({
      projectId: input.projectId,
      linearId: task.linearId,
      updates: { status: LINEAR_STATUSES.planReady },
    });

    return {
      success: true,
      phase: 'technical_plan',
      message: `Technical plan generated for task ${task.identifier}`,
      plan: result.plan,
    };
  } catch (error) {
    // Update status to Plan Failed
    try {
      const task = await syncLinearTask({
        taskId: input.taskId,
        projectId: input.projectId,
      });

      await updateLinearTask({
        projectId: input.projectId,
        linearId: task.linearId,
        updates: { status: LINEAR_STATUSES.planFailed },
      });
    } catch (updateError) {
      // Log but don't throw - original error is more important
      console.error('Failed to update status to planFailed:', updateError);
    }

    // Throw original error
    throw ApplicationFailure.create({
      message: `Technical plan workflow failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
      type: 'TechnicalPlanWorkflowFailure',
      cause: error instanceof Error ? error : undefined,
    });
  }
}
